linters:
  enable:
    - revive
    - govet
    - staticcheck
    - unused
    - asasalint
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - ginkgolinter
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosimple
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - ifshort
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - maligned
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - usestdlibvars
    - unparam
    - unused
    - varcheck
    - varnamelen
    - whitespace

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 30 
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 0.0
    # Should ignore tests.
    # Default: false
    skip-tests: true

issues:
  exclude-use-default: false
  exclude-rules:
    - linters: ["golint"]
      text: "exported function.*should have comment"

run:
  timeout: 5m
